from .bakmaz import fetch_bakmaz_prices
from .boso import fetch_boso_prices
from .djelo import fetch_djelo_prices
from .djelo_vodice import fetch_djelo_vodice_prices
from .eurospin import fetch_eurospin_prices
from .kaufland import fetch_kaufland_prices
from .konzum import fetch_konzum_prices
from .ktc import fetch_ktc_prices
from .lidl import fetch_lidl_prices
from .metro import fetch_metro_prices
from .ntl import fetch_ntl_prices
from .plodine import fetch_plodine_prices
from .ribola import fetch_ribola_prices
from .spar import fetch_spar_prices
from .studenac import fetch_studenac_prices
from .tommy import fetch_tommy_prices
from .trgovina_krk import fetch_trgovina_krk_prices
from .zabac import fetch_zabac_prices